### ISSUE TITLE
Quick search - Error 500 on back-end when searching for a bbs

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#245]
To reproduce, search for "grott" for example. It returns the following error : 
`error: An internal error occurred when getting Search entity with the following query [object Object]: TypeError: replacementKeys.forEach is not a function`

**Comment by Clm-Roig** [comment]
**UPDATE**
The error occurs when we get a result of type "bbs", in the MappingV1Service. _replacementKeys_ is not working properly.

**Comment by Clm-Roig** [comment]
Regression introduced by https://github.com/GrottoCenter/Grottocenter3/commit/77695dc156077dfdcb60ed17230545206ba8ad05#diff-95eecef80d6af0a4720822528493d243

The Object.assign() was replaced by the spread operator but it's not working properly. I'm working on a fix.

**Comment by Clm-Roig** [comment]
Fixed by #246, I close.
